### ISSUE TITLE
@Header for auth token

### ISSUE THREAD

**Issue by NeoLSN** [yggdrasilts/axiosfit#25]
I need to add a header with user token. I can't find my way to add it. Can you add this decorator for inserting dynamic headers?

something like this in `Retrofit`
```
@GET("user")
Call<User> getUser(@Header("Authorization") String authorization)
```

**Comment by telco2011** [comment]
Hi @NeoLSN 

At this stage, the header decorator still pending but you can use interceptors to add authorization token meanwhile. Something like the following code:

```
export class AuthInterceptorRequest implements AxiosfitRequestInterceptor {
  onRequest(config: AxiosRequestConfig): AxiosRequestConfig | Promise<AxiosRequestConfig> {
    config.headers['authorization'] = 'Bearer token';
    return config;
  }
}
```

And add the interceptor to your Axiosfit service:

```
@HTTP()
@Interceptors(AuthInterceptorRequest)
export class MyAxiosfitService {
  private static readonly serviceName = 'MyAxiosfitService';

  @GET('/get')
  public performGetRequestAuthenticated(): Observable<AxiosResponse<string>> {
    return null;
  }
}
```

I have also added this feature to be created in the next version 0.9.0 planned for the end of this month.

Let me know if you have more questions or you feel that more features are needed.

Also, I am planning to create a roadmap, maybe during version 0.10.0 creation, to let the community know which features will be implemented.
